name: Cypress

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: install modules
        working-directory: ./cypress-v2
        run: npm ci
      - name: execute tests
        working-directory: ./cypress-v2
        run: npm run test
