name: WebdriverIO V2

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: install modules
        working-directory: ./web-wdio-v2
        run: npm ci
      - name: execute tests
        working-directory: ./web-wdio-v2
        run: npm run test:webdriver
      - name: report artifact
        uses: actions/upload-artifact@v5
        with:
          name: report
          path: web-wdio/report/report.html
      - name: junit report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          report_paths: web-wdio-v2/report/report.xml
          fail_on_failure: true
