name: WebdriverIO Web Selenium

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: install modules
        working-directory: ./desktop-web
        run: npm ci
      - name: execute tests
        working-directory: ./desktop-web
        run: npm run test:selenium
      - name: report artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: desktop-web/report/report.html
      - name: junit report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: desktop-web/report/report.xml
          fail_on_failure: true
